title: "継続にっき"
baseurl: ""
url: ""

twitter_username: k_tsj
github_username:  k-tsj

# Build settings
timezone: Asia/Tokyo
permalink: /:year/:month/:day/:title:output_ext

theme: minima
minima:
  date_format: "%Y-%m-%d"

plugins:
  - jekyll-feed
